name: example
description: An example application using a code generator enabling sum-types in Dart.
version: 0.1.0
homepage: https://github.com/werediver/sum-types.dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  json_annotation:
  meta:
  sum_types:

dev_dependencies:
  build_runner:
  dependency_validator:
  json_serializable:
  sum_types_generator:
