name: sum_types_generator
description: sum_types and sum_types_generator packages together define a code generator enabling sum-types in Dart.
version: 0.2.0+1
homepage: https://github.com/werediver/sum-types-dart
author: Raman Fedaseyeu <raman.fedaseyeu@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  sum_types: ^0.2.0
  meta: ^1.1.0
  build: ^1.1.0
  analyzer: '>=0.36.4 <0.39.0'
  source_gen: ^0.9.2

dev_dependencies:
  dependency_validator:
