name: housekeeper
description: A housekeeping tool facilitating automation and CI needs around sum_types project.
version: 0.1.0
homepage: https://github.com/werediver/sum-types-dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta:
  path:

dev_dependencies:
  dependency_validator:

executables:
  housekeeper:

dependency_validator:
  exclude:
    - 'example/**'
  ignore:
    - sum_types_generator
    - json_serializable
